# -*- coding: utf-8 -*-
"""News.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GdauRE7_3OJ9SlZPbHmpKNJ7zTojXSOy
"""

from google.colab import drive
drive.mount('drive')

"""# It is a simple spam detection model


lets import the modules we need
"""

import pandas as pd
import spacy
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report

df = pd.read_csv('/content/drive/MyDrive/Fake_Real_Data.csv')
df.head()

print(f'total data: {len(df)}')
print(df.label.value_counts())

"""Encoding class with labels"""

df['Label_num'] = df['label'].map({'Fake':0,'Real':1})
df.head()

"""# spacy:
spaCy is an open-source natural language processing (NLP) library in Python. It is designed to be efficient, fast, and production-ready. spaCy provides pre-trained models for various languages, including English, to perform tasks such as tokenization, part-of-speech tagging, named entity recognition, and more.

# en_core_web_sm:
The en_core_web_sm model in spaCy is a small English language model provided by spaCy. Here are some key details about this model:

Size: Small (sm)
Pipeline: The model includes a basic NLP pipeline with essential components, such as tokenization, part-of-speech tagging, dependency parsing, named entity recognition, but without certain features like word vectors.
Word Vectors: Unlike the larger models (such as en_core_web_md and en_core_web_lg), the small model (en_core_web_sm) does not come with word vectors. Word vectors are multi-dimensional representations of words in a continuous vector space that capture semantic similarities.
Resource Requirements: The small size of the model makes it faster and requires less memory compared to larger models. This makes it suitable for applications where resource constraints are a concern.to install
"""

!python -m spacy download en_core_web_sm

nlp = spacy.load('en_core_web_sm')

"""Computer don't know Language like us. They only know numbers. So we need to convert the text into vectors so that computer can understand text-to-vector is done by"""

df['input_vector'] = df['Text'].apply(lambda x : nlp(x).vector)

df.head()

Xtrain,Xtest,ytrain,ytest = train_test_split(df.input_vector.values,df.Label_num,test_size=0.2)
Xtrain

"""In here the data is arranged in such a way that everything is a numpy array inside a numpy array so we need to convert them to a 2-dimensional array"""

Xtrain_2d = np.stack(Xtrain)
Xtest_2d = np.stack(Xtest)
Xtrain_2d

"""we are using a naive bayes classifier
naive bayes will not work if vector has negative numbers so we will scale the vector
"""

scaler = MinMaxScaler()

Xtrain_scaled = scaler.fit_transform(Xtrain_2d)
Xtest_scaled = scaler.transform(Xtest_2d)

"""# Naive Bayes Model:
Naive Bayes is a simple and probabilistic classification algorithm based on Bayes' theorem. It is a supervised machine learning algorithm commonly used for classification tasks, such as spam filtering, sentiment analysis, and document categorization

# Naive Assumption:
The "naive" part of Naive Bayes comes from the assumption that features are conditionally independent given the class label. This means that the presence or absence of a particular feature does not affect the presence or absence of any other feature. While this assumption is often not true in practice, it simplifies the model and makes it computationally efficient
"""

model = MultinomialNB()

"""Lets train the model"""

model.fit(Xtrain_scaled,ytrain)

"""Lets predict"""

y_pred = model.predict(Xtest_scaled)

"""lets evaluate the matrix"""

report = classification_report(ytest,y_pred)
print(report)

"""Wow accuracy is 0.93 which is 93%"""

label = {
    1:'real',
    0:'fake'
}

def prediction(text):
    input_vector = nlp(text).vector
    input_vector = input_vector.reshape(1, -1)
    scaled_vector = scaler.transform(input_vector)
    pred = model.predict(scaled_vector)
    return label[pred.item()]

prediction("Americans, but prompting criticism that the plan favors business and the rich and could add trillions of dollars to the deficit. The proposal drew a swift, skeptical response from Senator Bob Corker, a leading")

prediction("Trump Falls Flat On His Face In Israel, Doesnâ€™t Know Heâ€™s In The Middle East (VIDEO) Donald Trump has made a habit of embarrassing America in front of other world leaders, but on Monday he outdid himself.Kicking the week off, Trump outed Israel for being the source of intelligence information that he d given to Russia   a move that disgusted Israeli Prime Minister Benjamin Netanyahu. However, he was far from done ruining America s reputation. As he spoke in Israel, Trump stated that he d just gotten back from the Middle East, completely oblivious to the fact that Israel is actually IN the Middle East. Trump said: Our Secretary of State has done a great job. We just got back from the Middle East, Saudi Arabia, and we were treated incredibly well. It s almost too ridiculous to be true, but then again, what else can we expect from Trump? You can watch the incident below, and pay attention to the reaction of Israeli Ambassador Ron Dermer, who tries to disguise a very obvious facepalm by running his fingers through his hair.Oh man, watch Israeli ambassador Ron Dermer (on right couch) react when Trump says in Israel We just got back from the Middle East.  pic.twitter.com/x7nb4uvqpR  (((Yair Rosenberg))) (@Yair_Rosenberg) May 22, 2017It doesn t get much more humiliating than this. Already, the White House has had to defend several of Trump s mistakes during his international tour, citing  exhaustion  as the primary excuse for his pathetic performance (it s only been a few days). However, we all know that Trump is actually THAT dumb and doesn t know anything about other countries or how the world works.One can only imagine how hard everyone in the room had to concentrate to avoid correcting or laughing at Trump after such an insane f*ckup. Trump has proven, once again, that America s current president is a joke, and no one can take him seriously.Featured image via screen capture from embedded video ")

